"""add migrations for the social icons hero and about

Revision ID: 676d2e3cfc1c
Revises: 3f346c4e5883
Create Date: 2026-08-25 00:38:30.958563

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '676d2e3cfc1c'
down_revision: Union[str, Sequence[str], None] = '3f346c4e5883'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
